### ISSUE TITLE
Update TOS to include language about proxy service

### ISSUE THREAD

**Issue by mattdricker** [hypothesis/agreements#15]
Proposed language to be included under _Using the Services_:

**Use of Hypothesis’ proxy services (e.g. via.hypothes.is) is strictly limited to facilitating Hypothesis’ annotation services in accordance with the Terms of Service outlined in this document. Any other use of Hypothesis’ proxy services is prohibited, and may result in suspension or termination of user’s account, or other appropriate action as necessary.**

**Comment by xolotl** [comment]
To avoid the ungainly possessives with the Hypothesis name, I would suggest this slight revision to:

Use of Hypothesis proxy services (e.g. via.hypothes.is) is strictly limited to facilitating Hypothesis annotation services in accordance with the Terms of Service outlined in this document. Any other use of Hypothesis proxy services is prohibited, and may result in suspension or termination of user accounts, or other appropriate action as necessary.

**Comment by xolotl** [comment]
We also need to decide where in the ToS to place this language.

**Comment by mattdricker** [comment]
Good call on the lack of gainliness.

Regarding placement, see
> Proposed language to be included under _Using the Services_:

**Comment by ajpeddakotla** [comment]
Apologies for the delay here.....hopefully this isn't too late to comment on this.

Minor change (remove suspension of user accounts, since we can't do that)

>Use of Hypothesis proxy services (e.g. via.hypothes.is) is strictly limited to facilitating Hypothesis annotation services in accordance with the Terms of Service outlined in this document. Any other use of Hypothesis proxy services is prohibited, and may result in termination of user accounts, or other appropriate action as necessary.

The location of it that @mattdricker notes is good.

**Comment by lyzadanger** [comment]
Peanut gallery is curious as to the difference between _limited_ and _strictly limited_.

**Comment by mattdricker** [comment]
Good question, actually! I don't know, other than "strictly limited" sounding way more severe.

**Comment by xolotl** [comment]
Committed here with 40dd6b929d7829f93523bd57d63805f02a4cf802 and posted to website.
