### ISSUE TITLE
Abide by Google Analytics requirements

### ISSUE THREAD

**Issue by tilgovi** [hypothesis/agreements#2]
http://www.google.com/analytics/terms/us.html

Section 7, relevant part reproduced below:

> You must post a Privacy Policy and that Privacy Policy must provide notice of Your use of cookies that are used to collect data. You must disclose the use of Google Analytics, and how it collects and processes data. This can be done by displaying a prominent link to the site “How Google uses data when you use our partners' sites or apps”, (located at www.google.com/policies/privacy/partners/, or any other URL Google may provide from time to time).

**Comment by lenazun** [comment]
Fixed by de1da43
